pipeline {
    agent any

    stages {
        stage('Pre-Build: Fetch GitHub Repositories') {
            steps {
                build job: 'fetch_repos' // Call the pre-build job
            }
        }

        stage('User Selects Repository') {
            steps {
                script {
                    def repoChoices = readFile('/var/jenkins_home/workspace/fetch_repos/github_branches.json').trim().split("\n")

                    properties([
                        parameters([
                            choice(name: 'GIT_REPO', choices: repoChoices.join("\n"), description: 'Select the repository to build')
                        ])
                    ])
                }
            }
        }
    }
}