pipeline {
    agent any

    stages {

        stage('Package') {
            when {
                expression { params.Options == 'Deploy'}
            }
            steps {
                dir('lambda') {
                    sh 'bash package.sh'
                }
            }
        }

        stage('DeployInfrastructure') {
            when {
                expression { params.Options == 'Deploy' }
            }
            steps {
                    
                dir('lambda') {
                    sh 'terraform init'
                    sh 'terraform plan -out=plan.tfplan'
                    sh 'terraform apply -auto-approve plan.tfplan'
                }
                    
            }
        }

        stage('DestroyInfrastructure') {
            when {
                expression { params.Options == 'Destroy' }
            }
            steps {
                dir('lambda') {
                    sh 'terraform init'
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace'
            cleanWs()
        }
    }
}